/// <reference lib="webworker" />
/* eslint-disable no-restricted-globals */

// This service worker can be customized!
// See https://developers.google.com/web/tools/workbox/modules
// for the list of available Workbox modules, or add any other
// code you'd like.
// You can also remove this file if you'd prefer not to use a
// service worker, and the Workbox build step will be skipped.

import ExchangeRateApiService from '@common/api/exchange-rate-api.service';
import { Currency } from '@common/api/exchange-rate-api.types';
import { ConversionNotification, ExchangeRateNotification } from '@common/notifications';
import { clientsClaim, setCacheNameDetails } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { createHandlerBoundToURL, precacheAndRoute } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { NetworkFirst, StaleWhileRevalidate } from 'workbox-strategies';

declare const self: ServiceWorkerGlobalScope;

const dayInSeconds = 24 * 60 * 60;
const twoDaysInSeconds = 2 * dayInSeconds;

const EXCHANGE_RATE_API_CACHE = 'exchange-rate-api-cache-v1';
const IMAGE_CACHE = 'image-cache-v1';
const PRECACHE = 'precache-v1';

const currentCaches = [PRECACHE, EXCHANGE_RATE_API_CACHE, IMAGE_CACHE];

clientsClaim();

// sets the precache name
setCacheNameDetails({
  precache: PRECACHE,
});

// Precache all of the assets generated by your build process.
// Their URLs are injected into the manifest variable below.
// This variable must be present somewhere in your service worker file,
// even if you decide not to use precaching. See https://cra.link/PWA
precacheAndRoute(self.__WB_MANIFEST);

// Set up App Shell-style routing, so that all navigation requests
// are fulfilled with your index.html shell. Learn more at
// https://developers.google.com/web/fundamentals/architecture/app-shell
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being fulfilled by index.html.
  ({ request, url }: { request: Request; url: URL }) => {
    // If this isn't a navigation, skip.
    if (request.mode !== 'navigate') {
      return false;
    }

    // If this is a URL that starts with /_, skip.
    if (url.pathname.startsWith('/_')) {
      return false;
    }

    // If this looks like a URL for a resource, because it contains
    // a file extension, skip.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true to signal that we want to use the handler.
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html'),
);

// An example runtime caching route for requests that aren't handled by the
// precache, in this case same-origin .png requests like those from in public/
registerRoute(
  // Add in any other file extensions or routing criteria as needed.
  ({ url }) => url.origin === self.location.origin && url.pathname.endsWith('.png'),
  // Customize this strategy as needed, e.g., by changing to CacheFirst.
  new StaleWhileRevalidate({
    cacheName: IMAGE_CACHE,
    plugins: [
      // Ensure that once this runtime cache reaches a maximum size the
      // least-recently used images are removed.
      new ExpirationPlugin({ maxEntries: 50 }),
    ],
  }),
);

// This allows the web app to trigger skipWaiting via
// registration.waiting.postMessage({type: 'SKIP_WAITING'})
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  } else if (event.data && event.data.type === ExchangeRateNotification['type']) {
    const { baseCurrency, targetCurrency } = event.data.data as ExchangeRateNotification['data'];

    setTimeout(() => {
      fetchExchangeRateAndNotify(baseCurrency, targetCurrency);
    }, 600);
  }

  if (event.data && event.data.type === ConversionNotification['type']) {
    console.log('Received message from CurrencyConverter:', event.data.data);
    const { baseCurrency, targetCurrency, baseCurrencyAmount, targetCurrencyAmount } = event.data.data as ConversionNotification['data'];

    showConversionNotification(baseCurrency, targetCurrency, baseCurrencyAmount, targetCurrencyAmount);
  }
});

function showConversionNotification(baseCurrency: string, targetCurrency: string, baseAmount: number, targetAmount: number) {
  console.log('Showing conversion notification:', { baseCurrency, targetCurrency, baseAmount, targetAmount });

  showNotification('Currency Conversion', `${baseAmount} ${baseCurrency} = ${targetAmount} ${targetCurrency}`, 'currency-conversion');
}

function showNotification(title: string, body: string, tag: string) {
  self.registration.showNotification(title, {
    body,
    icon: '/icon.png',
    tag,
  });
}

async function fetchExchangeRateAndNotify(baseCurrency: Currency, targetCurrency: Currency) {
  try {
    const exchangeRateApiService = ExchangeRateApiService.getInstance();
    const response = await exchangeRateApiService.getExchangeRateForCurrency(baseCurrency);

    if (response.result === 'error') {
      showNotification('Exchange Rate Notification', `The exchange rate from ${baseCurrency} to ${targetCurrency} is unknown.`, 'exchange-rate');

      console.error('Error fetching currency data:', response['error-type']);

      return;
    }
    const rate = response.conversion_rates[targetCurrency];

    showNotification('Exchange Rate Notification', `The exchange rate from ${baseCurrency} to ${targetCurrency} is ${rate}.`, 'exchange-rate');
  } catch (error) {
    console.error('Error fetching exchange rate:', error);
  }
}

// Any other custom service worker logic can go here.

// Cache the exchange rate API responses
registerRoute(
  ({ url }) => url.href.startsWith(ExchangeRateApiService.BASE_URL),
  new NetworkFirst({
    cacheName: EXCHANGE_RATE_API_CACHE,
    plugins: [new ExpirationPlugin({ maxEntries: 70, maxAgeSeconds: twoDaysInSeconds })],
  }),
);

// Immediately activate the new service worker
self.addEventListener('install', function () {
  self.skipWaiting();
});

// Delete old caches during the activate event
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((cacheNames) => {
        return cacheNames.filter((cacheName) => !currentCaches.includes(cacheName));
      })
      .then((cachesToDelete) => {
        return Promise.all(
          cachesToDelete.map((cacheToDelete) => {
            return caches.delete(cacheToDelete);
          }),
        );
      })
      .then(() => self.clients.claim()),
  );
});
